worker_processes	1;

events
{
    worker_connections	1024;
}

http 
{
	include				mime.types;
	default_type		application/octet-stream;
	sendfile			on;
	keepalive_timeout	65;

	server
	{
		#SSL
		listen				443 ssl;						# serveur ecoute son port 443 et avec le protocole ssl
		ssl_protocols		TLSv1.2 TLSv1.3;				# versions ssl acceptes
		ssl_certificate		/etc/nginx/ssl/inception.crt;	# emplacement du certificat ssl
		ssl_certificate_key	/etc/nginx/ssl/inception.key;	# emplacement de la cle ssl

		#root
		root		/var/www/wordpress;						# path du dossier ou les uri vont etre recherches
		server_name	pbret.42.fr;							# nom de domaine du serveur
		index		index.php index.html index.htm;			# si aucune uri indique, le serv va tenter de servir 
															# l'une apres l autre si la precedente n'existe pas

		location /											# indique au serveur de rechercher dans le root le uri envoye.
		{
			try_files $uri $uri/ =404;						# cherche soit un fichier soit un dossier -> si pas trouve serre la page 404
		}
	
		location ~ \.php$									# le serveur va redirigier toutes les uri finissants par .php vers le container wordpress
		{ 
			include			snippets/fastcgi-php.conf;		# Librairie de FastCGI (protocole de communication) pour que nginx communique avec PHP-FPM
			fastcgi_pass	wordpress:9000;					# Comment renvoyer les requetes php sur le port 9000 du conteneur wordpress
		}
	}
}
